---

- name: Install bacula client packages
  package:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: False
  with_items:
    - 'bacula-fd'

- name: Configure fd
  template:
    src: "etc/bacula/bacula-fd.conf.j2"
    dest: '/etc/bacula/bacula-fd.conf'
    owner: 'root'
    group: 'bacula'
    mode: '0440'
  notify: [ 'Check bacula-fd config' ]

- name: Configure fd -> dir-client
  template:
    src: "etc/bacula/conf.d/dir-client.conf.j2"
    dest: '/etc/bacula/conf.d/dir-client-{{ bacula__conf_client.name | replace(".","_") }}.conf'
    owner: 'root'
    group: 'bacula'
    mode: '0440'
  delegate_to: '{{ bacula__conf_dir.name_ansible }}'
  notify: [ 'Check fd -> dir config' ]

- name: Configure fd -> dir-job
  template:
    src: "etc/bacula/conf.d/dir-job.conf.j2"
    dest: '/etc/bacula/conf.d/dir-job-{{ bacula__conf_client.name | replace(".","_") }}-{{ item.name }}.conf'
    owner: 'root'
    group: 'bacula'
    mode: '0440'
  delegate_to: '{{ bacula__conf_dir.name_ansible }}'
  notify: [ 'Check fd -> dir config' ]
  when: bacula__conf_client_job|d()
  with_items: '{{ bacula__conf_client_job }}'

- name: Configure fd -> dir-jobDefs
  template:
    src: "etc/bacula/conf.d/dir-jobDefs.conf.j2"
    dest: '/etc/bacula/conf.d/dir-jobDefs-{{ item.name }}.conf'
    owner: 'root'
    group: 'bacula'
    mode: '0440'
  delegate_to: '{{ bacula__conf_dir.name_ansible }}'
  notify: [ 'Check fd -> dir config' ]
  when: bacula__conf_client_jobDefs|d()
  with_items: '{{ bacula__conf_client_jobDefs }}'

- name: Configure fd -> dir-FileSet
  template:
    src: "etc/bacula/conf.d/dir-fileset.conf.j2"
    dest: '/etc/bacula/conf.d/dir-fileset-{{ item.name }}.conf'
    owner: 'root'
    group: 'bacula'
    mode: '0440'
  delegate_to: '{{ bacula__conf_dir.name_ansible }}'
  notify: [ 'Check fd -> dir config' ]
  when: bacula__conf_client_FileSet|d()
  with_items: '{{ bacula__conf_client_FileSet }}'

- name: Configure fd -> dir-storage
  template:
    src: "etc/bacula/conf.d/dir-storage.conf.j2"
    dest: '/etc/bacula/conf.d/dir-storage-{{ bacula__conf_client.name | replace(".","_") }}.conf'
    owner: 'root'
    group: 'bacula'
    mode: '0440'
  delegate_to: '{{ bacula__conf_dir.name_ansible }}'
  notify: [ 'Check fd -> dir config' ]
  when: bacula__conf_client_job|d()

- name: Create directories fd -> sd-device
  file:
    path:   '{{ item.path }}'
    state:  '{{ item.state  | default("directory") }}'
    owner:  '{{ item.owner  | default("root") }}'
    group:  '{{ item.group  | default("root") }}'
    mode:   '{{ item.mode   | default("0755") }}'
  with_items:
    - { path: '{{ bacula__conf_sd.device_path }}/{{ bacula__conf_client.name | replace(".","_") }}', owner: 'bacula' }
  delegate_to: '{{ bacula__conf_sd.name_ansible }}'
  when: bacula__conf_client_job|d()

- name: Configure fd -> sd-device
  template:
    src: "etc/bacula/conf.d/sd-device.conf.j2"
    dest: '/etc/bacula/conf.d/sd-device-{{ bacula__conf_client.name | replace(".","_") }}.conf'
    owner: 'root'
    group: 'bacula'
    mode: '0440'
  delegate_to: '{{ bacula__conf_sd.name_ansible }}'
  notify: [ 'Check fd -> sd config' ]
  when: bacula__conf_client_job|d()

- name: Configure fd -> dir-pool
  template:
    src: "etc/bacula/conf.d/dir-pool.conf.j2"
    dest: '/etc/bacula/conf.d/dir-pool-{{ bacula__conf_client.name | replace(".","_") }}-{{ item.name }}.conf'
    owner: 'root'
    group: 'bacula'
    mode: '0440'
  delegate_to: '{{ bacula__conf_dir.name_ansible }}'
  notify: [ 'Check fd -> dir config' ]
  when: bacula__conf_client_job|d()
  with_items: '{{ bacula__conf_client_job }}'

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
