---

- name: Install bacula client packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: False
  with_items:
    - 'bacula-fd'

- name: Configure fd
  template:
    src: "etc/bacula/bacula-fd.conf.j2"
    dest: '/etc/bacula/bacula-fd.conf'
    owner: 'root'
    group: 'root'
    mode: '0440'
  notify: [ 'bacula-fd restart' ]

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
